### ISSUE TITLE
[11.0]Unstable behavior when installing many modules

### ISSUE THREAD

**Issue by SalahAdDin** [OmniaGit/odooplm#4]
I'm testing these modules for a company.

I installed these modules previously and I had no problems when my apps were under 11.

But after install more than 15 i can see that odoo unistall these modules all time.

I saw the next traceback:
```
2018-06-20 11:49:43,093 14 ERROR rotafilo odoo.sql_db: bad query: b'ALTER TABLE "mrp_bom_line" ALTER COLUMN "type" SET NOT NULL'
ERROR: column "type" contains null values

2018-06-20 11:49:43,094 14 WARNING rotafilo odoo.schema: Table 'mrp_bom_line': unable to set NOT NULL on column 'type'!
If you want to have it, you should update the records and execute manually:
ALTER TABLE "mrp_bom_line" ALTER COLUMN "type" SET NOT NULL
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/sql.py", line 109, in set_not_null
    cr.execute(query)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.IntegrityError: column "type" contains null values

2018-06-20 11:49:44,218 14 WARNING rotafilo odoo.modules.registry: Models have no table: report.plm_document.user, report.plm_files.partner, report.plm_document.wall.
2018-06-20 11:49:44,222 14 ERROR rotafilo odoo.modules.registry: Model report.plm_document.user has no table.
2018-06-20 11:49:44,222 14 ERROR rotafilo odoo.modules.registry: Model report.plm_document.wall has no table.
2018-06-20 11:49:44,222 14 ERROR rotafilo odoo.modules.registry: Model report.plm_files.partner has no table.
2018-06-20 11:49:47,120 14 WARNING rotafilo odoo.models: ir.actions.act_window.create() includes unknown fields: view_id_search
2018-06-20 11:49:47,730 14 WARNING rotafilo odoo.models: ir.actions.report.create() includes unknown fields: header
2018-06-20 11:49:47,738 14 WARNING rotafilo odoo.models: ir.actions.report.create() includes unknown fields: header
2018-06-20 11:49:47,744 14 WARNING rotafilo odoo.models: ir.actions.report.create() includes unknown fields: header
2018-06-20 11:49:47,751 14 WARNING rotafilo odoo.models: ir.actions.report.create() includes unknown fields: header
2018-06-20 11:49:47,757 14 WARNING rotafilo odoo.models: ir.actions.report.create() includes unknown fields: header
2018-06-20 11:49:47,763 14 WARNING rotafilo odoo.models: ir.actions.report.create() includes unknown fields: header
2018-06-20 11:49:47,772 14 WARNING rotafilo odoo.models: ir.actions.report.create() includes unknown fields: header
2018-06-20 11:49:49,004 14 WARNING rotafilo odoo.modules.registry: Models have no table: report.plm_document.user, report.plm_files.partner, report.plm_document.wall.
2018-06-20 11:49:49,009 14 ERROR rotafilo odoo.modules.registry: Model report.plm_document.user has no table.
2018-06-20 11:49:49,009 14 ERROR rotafilo odoo.modules.registry: Model report.plm_document.wall has no table.
2018-06-20 11:49:49,009 14 ERROR rotafilo odoo.modules.registry: Model report.plm_files.partner has no table.
2018-06-20 11:51:36,801 22 WARNING ? odoo.addons.base.ir.ir_cron: Skipping database rotafilo because of modules to install/upgrade/remove.
2018-06-20 11:51:56,905 18 ERROR rotafilo odoo.modules.graph: module plm_cutted_parts: Unmet dependencies: plm, plm_engineering
2018-06-20 11:51:56,905 18 ERROR rotafilo odoo.modules.graph: module plm_suspended: Unmet dependencies: plm
2018-06-20 11:51:56,905 18 ERROR rotafilo odoo.modules.graph: module plm_automatic_weight: Unmet dependencies: plm
2018-06-20 11:51:56,905 18 ERROR rotafilo odoo.modules.graph: module plm_automate_normal_bom: Unmet dependencies: plm, plm_engineering
2018-06-20 11:51:56,905 18 ERROR rotafilo odoo.modules.graph: module plm_spare: Unmet dependencies: plm
2018-06-20 11:51:56,905 18 ERROR rotafilo odoo.modules.graph: module plm_report_language_helper: Unmet dependencies: plm, plm_spare
2018-06-20 11:51:56,905 18 ERROR rotafilo odoo.modules.graph: module plm_date_bom: Unmet dependencies: plm
2018-06-20 11:51:56,906 18 ERROR rotafilo odoo.modules.graph: module plm_product_description_language_helper: Unmet dependencies: plm
2018-06-20 11:51:56,906 18 ERROR rotafilo odoo.modules.graph: module plm_web_revision: Unmet dependencies: plm
2018-06-20 11:51:56,906 18 ERROR rotafilo odoo.modules.graph: module plm_engineering: Unmet dependencies: plm
2018-06-20 11:51:56,906 18 ERROR rotafilo odoo.modules.graph: module plm_pack_and_go: Unmet dependencies: plm
2018-06-20 11:52:29,895 21 WARNING ? odoo.addons.base.ir.ir_cron: Skipping database rotafilo because of modules to install/upgrade/remove.
2018-06-20 11:52:38,855 22 WARNING ? odoo.addons.base.ir.ir_cron: Skipping database rotafilo because of modules to install/upgrade/remove.
2018-06-20 11:53:30,910 21 WARNING ? odoo.addons.base.ir.ir_cron: Skipping database rotafilo because of modules to install/upgrade/remove.
2018-06-20 11:53:40,960 22 WARNING ? odoo.addons.base.ir.ir_cron: Skipping database rotafilo because of modules to install/upgrade/remove.
2018-06-20 11:54:31,919 21 WARNING ? odoo.addons.base.ir.ir_cron: Skipping database rotafilo because of modules to install/upgrade/remove.
2018-06-20 11:54:42,982 22 WARNING ? odoo.addons.base.ir.ir_cron: Skipping database rotafilo because of modules to install/upgrade/remove.
2018-06-20 11:55:32,966 21 WARNING ? odoo.addons.base.ir.ir_cron: Skipping database rotafilo because of modules to install/upgrade/remove.
2018-06-20 11:55:45,082 22 WARNING ? odoo.addons.base.ir.ir_cron: Skipping database rotafilo because of modules to install/upgrade/remove.
2018-06-20 11:55:52,481 18 ERROR rotafilo odoo.modules.graph: module plm_cutted_parts: Unmet dependencies: plm, plm_engineering
2018-06-20 11:55:52,481 18 ERROR rotafilo odoo.modules.graph: module plm_suspended: Unmet dependencies: plm
2018-06-20 11:55:52,481 18 ERROR rotafilo odoo.modules.graph: module plm_automatic_weight: Unmet dependencies: plm
2018-06-20 11:55:52,481 18 ERROR rotafilo odoo.modules.graph: module plm_automate_normal_bom: Unmet dependencies: plm, plm_engineering
2018-06-20 11:55:52,481 18 ERROR rotafilo odoo.modules.graph: module plm_spare: Unmet dependencies: plm
2018-06-20 11:55:52,481 18 ERROR rotafilo odoo.modules.graph: module plm_report_language_helper: Unmet dependencies: plm, plm_spare
2018-06-20 11:55:52,481 18 ERROR rotafilo odoo.modules.graph: module plm_date_bom: Unmet dependencies: plm
2018-06-20 11:55:52,481 18 ERROR rotafilo odoo.modules.graph: module plm_product_description_language_helper: Unmet dependencies: plm
2018-06-20 11:55:52,481 18 ERROR rotafilo odoo.modules.graph: module plm_web_revision: Unmet dependencies: plm
2018-06-20 11:55:52,481 18 ERROR rotafilo odoo.modules.graph: module plm_engineering: Unmet dependencies: plm
2018-06-20 11:55:52,481 18 ERROR rotafilo odoo.modules.graph: module plm_pack_and_go: Unmet dependencies: plm
2018-06-20 11:55:53,611 18 ERROR rotafilo odoo.sql_db: bad query: b'ALTER TABLE "res_config_settings" ALTER COLUMN "website_id" SET NOT NULL'
ERROR: column "website_id" contains null values

2018-06-20 11:55:53,611 18 WARNING rotafilo odoo.schema: Table 'res_config_settings': unable to set NOT NULL on column 'website_id'!
If you want to have it, you should update the records and execute manually:
ALTER TABLE "res_config_settings" ALTER COLUMN "website_id" SET NOT NULL
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/sql.py", line 109, in set_not_null
    cr.execute(query)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.IntegrityError: column "website_id" contains null values

2018-06-20 11:56:09,406 18 ERROR rotafilo odoo.modules.graph: module plm_cutted_parts: Unmet dependencies: plm, plm_engineering
2018-06-20 11:56:09,406 18 ERROR rotafilo odoo.modules.graph: module plm_suspended: Unmet dependencies: plm
2018-06-20 11:56:09,406 18 ERROR rotafilo odoo.modules.graph: module plm_automatic_weight: Unmet dependencies: plm
2018-06-20 11:56:09,406 18 ERROR rotafilo odoo.modules.graph: module plm_automate_normal_bom: Unmet dependencies: plm, plm_engineering
2018-06-20 11:56:09,406 18 ERROR rotafilo odoo.modules.graph: module plm_spare: Unmet dependencies: plm
2018-06-20 11:56:09,406 18 ERROR rotafilo odoo.modules.graph: module plm_report_language_helper: Unmet dependencies: plm, plm_spare
2018-06-20 11:56:09,406 18 ERROR rotafilo odoo.modules.graph: module plm_date_bom: Unmet dependencies: plm
2018-06-20 11:56:09,406 18 ERROR rotafilo odoo.modules.graph: module plm_product_description_language_helper: Unmet dependencies: plm
2018-06-20 11:56:09,406 18 ERROR rotafilo odoo.modules.graph: module plm_web_revision: Unmet dependencies: plm
2018-06-20 11:56:09,406 18 ERROR rotafilo odoo.modules.graph: module plm_engineering: Unmet dependencies: plm
2018-06-20 11:56:09,406 18 ERROR rotafilo odoo.modules.graph: module plm_pack_and_go: Unmet dependencies: plm
2018-06-20 11:56:09,422 18 ERROR rotafilo odoo.modules.graph: module plm_cutted_parts: Unmet dependencies: plm, plm_engineering
2018-06-20 11:56:09,422 18 ERROR rotafilo odoo.modules.graph: module plm_suspended: Unmet dependencies: plm
2018-06-20 11:56:09,422 18 ERROR rotafilo odoo.modules.graph: module plm_automatic_weight: Unmet dependencies: plm
2018-06-20 11:56:09,422 18 ERROR rotafilo odoo.modules.graph: module plm_automate_normal_bom: Unmet dependencies: plm, plm_engineering
2018-06-20 11:56:09,422 18 ERROR rotafilo odoo.modules.graph: module plm_spare: Unmet dependencies: plm
2018-06-20 11:56:09,422 18 ERROR rotafilo odoo.modules.graph: module plm_report_language_helper: Unmet dependencies: plm, plm_spare
2018-06-20 11:56:09,422 18 ERROR rotafilo odoo.modules.graph: module plm_date_bom: Unmet dependencies: plm
2018-06-20 11:56:09,422 18 ERROR rotafilo odoo.modules.graph: module plm_product_description_language_helper: Unmet dependencies: plm
2018-06-20 11:56:09,422 18 ERROR rotafilo odoo.modules.graph: module plm_web_revision: Unmet dependencies: plm
2018-06-20 11:56:09,422 18 ERROR rotafilo odoo.modules.graph: module plm_engineering: Unmet dependencies: plm
2018-06-20 11:56:09,422 18 ERROR rotafilo odoo.modules.graph: module plm_pack_and_go: Unmet dependencies: plm
2018-06-20 11:56:34,021 21 WARNING ? odoo.addons.base.ir.ir_cron: Skipping database rotafilo because of modules to install/upgrade/remove.
2018-06-20 11:56:47,181 22 WARNING ? odoo.addons.base.ir.ir_cron: Skipping database rotafilo because of modules to install/upgrade/remove.
2018-06-20 11:57:09,275 18 ERROR rotafilo odoo.sql_db: bad query: b'ALTER TABLE "mrp_bom_line" ALTER COLUMN "type" SET NOT NULL'
ERROR: column "type" contains null values

2018-06-20 11:57:09,276 18 WARNING rotafilo odoo.schema: Table 'mrp_bom_line': unable to set NOT NULL on column 'type'!
If you want to have it, you should update the records and execute manually:
ALTER TABLE "mrp_bom_line" ALTER COLUMN "type" SET NOT NULL
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/sql.py", line 109, in set_not_null
    cr.execute(query)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.IntegrityError: column "type" contains null values

2018-06-20 11:57:10,268 18 WARNING rotafilo odoo.modules.registry: Models have no table: report.plm_document.user, report.plm_files.partner, report.plm_document.wall.
2018-06-20 11:57:10,274 18 ERROR rotafilo odoo.modules.registry: Model report.plm_document.user has no table.
2018-06-20 11:57:10,274 18 ERROR rotafilo odoo.modules.registry: Model report.plm_document.wall has no table.
2018-06-20 11:57:10,274 18 ERROR rotafilo odoo.modules.registry: Model report.plm_files.partner has no table.
2018-06-20 11:57:13,098 18 WARNING rotafilo odoo.models: ir.actions.act_window.create() includes unknown fields: view_id_search
2018-06-20 11:57:13,684 18 WARNING rotafilo odoo.models: ir.actions.report.create() includes unknown fields: header
2018-06-20 11:57:13,689 18 WARNING rotafilo odoo.models: ir.actions.report.create() includes unknown fields: header
2018-06-20 11:57:13,695 18 WARNING rotafilo odoo.models: ir.actions.report.create() includes unknown fields: header
2018-06-20 11:57:13,701 18 WARNING rotafilo odoo.models: ir.actions.report.create() includes unknown fields: header
2018-06-20 11:57:13,708 18 WARNING rotafilo odoo.models: ir.actions.report.create() includes unknown fields: header
2018-06-20 11:57:13,714 18 WARNING rotafilo odoo.models: ir.actions.report.create() includes unknown fields: header
2018-06-20 11:57:13,724 18 WARNING rotafilo odoo.models: ir.actions.report.create() includes unknown fields: header
2018-06-20 11:57:14,940 18 WARNING rotafilo odoo.modules.registry: Models have no table: report.plm_document.user, report.plm_files.partner, report.plm_document.wall.
2018-06-20 11:57:14,945 18 ERROR rotafilo odoo.modules.registry: Model report.plm_document.user has no table.
2018-06-20 11:57:14,945 18 ERROR rotafilo odoo.modules.registry: Model report.plm_document.wall has no table.
2018-06-20 11:57:14,945 18 ERROR rotafilo odoo.modules.registry: Model report.plm_files.partner has no table.
2018-06-20 11:57:15,408 18 WARNING rotafilo odoo.models: ir.actions.server.create() includes unknown fields: condition
2018-06-20 11:57:15,443 18 WARNING rotafilo odoo.models: ir.actions.server.create() includes unknown fields: condition
2018-06-20 11:57:15,818 18 ERROR rotafilo odoo.sql_db: bad query: b'ALTER TABLE "mrp_bom_line" ALTER COLUMN "type" SET NOT NULL'
ERROR: column "type" contains null values

2018-06-20 11:57:15,819 18 WARNING rotafilo odoo.schema: Table 'mrp_bom_line': unable to set NOT NULL on column 'type'!
If you want to have it, you should update the records and execute manually:
ALTER TABLE "mrp_bom_line" ALTER COLUMN "type" SET NOT NULL
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/sql.py", line 109, in set_not_null
    cr.execute(query)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.IntegrityError: column "type" contains null values

2018-06-20 11:57:15,886 18 WARNING rotafilo odoo.modules.registry: Models have no table: report.plm_document.user, report.plm_files.partner, report.plm_document.wall.
2018-06-20 11:57:15,891 18 ERROR rotafilo odoo.modules.registry: Model report.plm_document.user has no table.
2018-06-20 11:57:15,891 18 ERROR rotafilo odoo.modules.registry: Model report.plm_document.wall has no table.
2018-06-20 11:57:15,891 18 ERROR rotafilo odoo.modules.registry: Model report.plm_files.partner has no table.
2018-06-20 11:57:16,510 18 WARNING rotafilo odoo.modules.registry: Models have no table: report.plm_document.user, report.plm_files.partner, report.plm_document.wall.
2018-06-20 11:57:16,514 18 ERROR rotafilo odoo.modules.registry: Model report.plm_document.user has no table.
2018-06-20 11:57:16,514 18 ERROR rotafilo odoo.modules.registry: Model report.plm_document.wall has no table.
2018-06-20 11:57:16,514 18 ERROR rotafilo odoo.modules.registry: Model report.plm_files.partner has no table.
2018-06-20 11:57:18,029 18 WARNING rotafilo odoo.modules.registry: Models have no table: report.plm_document.user, report.plm_files.partner, report.plm_document.wall.
2018-06-20 11:57:18,034 18 ERROR rotafilo odoo.modules.registry: Model report.plm_document.user has no table.
2018-06-20 11:57:18,034 18 ERROR rotafilo odoo.modules.registry: Model report.plm_document.wall has no table.
2018-06-20 11:57:18,034 18 ERROR rotafilo odoo.modules.registry: Model report.plm_files.partner has no table.
2018-06-20 11:57:18,569 18 WARNING rotafilo odoo.modules.registry: Models have no table: report.plm_document.user, report.plm_files.partner, report.plm_document.wall.
2018-06-20 11:57:18,574 18 ERROR rotafilo odoo.modules.registry: Model report.plm_document.user has no table.
2018-06-20 11:57:18,574 18 ERROR rotafilo odoo.modules.registry: Model report.plm_document.wall has no table.
2018-06-20 11:57:18,574 18 ERROR rotafilo odoo.modules.registry: Model report.plm_files.partner has no table.
2018-06-20 11:57:19,125 18 WARNING rotafilo odoo.modules.registry: Models have no table: report.plm_document.user, report.plm_files.partner, report.plm_document.wall.
2018-06-20 11:57:19,130 18 ERROR rotafilo odoo.modules.registry: Model report.plm_document.user has no table.
2018-06-20 11:57:19,131 18 ERROR rotafilo odoo.modules.registry: Model report.plm_document.wall has no table.
2018-06-20 11:57:19,131 18 ERROR rotafilo odoo.modules.registry: Model report.plm_files.partner has no table.
2018-06-20 11:57:19,732 18 WARNING rotafilo odoo.modules.registry: Models have no table: report.plm_document.user, report.plm_files.partner, report.plm_document.wall.
2018-06-20 11:57:19,737 18 ERROR rotafilo odoo.modules.registry: Model report.plm_document.user has no table.
2018-06-20 11:57:19,737 18 ERROR rotafilo odoo.modules.registry: Model report.plm_document.wall has no table.
2018-06-20 11:57:19,737 18 ERROR rotafilo odoo.modules.registry: Model report.plm_files.partner has no table.
2018-06-20 11:57:19,995 18 WARNING rotafilo odoo.models: ir.actions.report.create() includes unknown fields: header
2018-06-20 11:57:20,002 18 WARNING rotafilo odoo.models: ir.actions.report.create() includes unknown fields: header
2018-06-20 11:57:20,330 18 WARNING rotafilo odoo.modules.registry: Models have no table: report.plm_document.user, report.plm_files.partner, report.plm_document.wall.
2018-06-20 11:57:20,335 18 ERROR rotafilo odoo.modules.registry: Model report.plm_document.user has no table.
2018-06-20 11:57:20,335 18 ERROR rotafilo odoo.modules.registry: Model report.plm_document.wall has no table.
2018-06-20 11:57:20,335 18 ERROR rotafilo odoo.modules.registry: Model report.plm_files.partner has no table.
2018-06-20 11:57:20,965 18 WARNING rotafilo odoo.modules.registry: Models have no table: report.plm_document.user, report.plm_files.partner, report.plm_document.wall.
2018-06-20 11:57:20,970 18 ERROR rotafilo odoo.modules.registry: Model report.plm_document.user has no table.
2018-06-20 11:57:20,970 18 ERROR rotafilo odoo.modules.registry: Model report.plm_document.wall has no table.
2018-06-20 11:57:20,970 18 ERROR rotafilo odoo.modules.registry: Model report.plm_files.partner has no table.
2018-06-20 11:57:21,367 18 WARNING rotafilo odoo.modules.registry: Models have no table: report.plm_document.user, report.plm_files.partner, report.plm_document.wall.
2018-06-20 11:57:21,373 18 ERROR rotafilo odoo.modules.registry: Model report.plm_document.user has no table.
2018-06-20 11:57:21,373 18 ERROR rotafilo odoo.modules.registry: Model report.plm_document.wall has no table.
2018-06-20 11:57:21,373 18 ERROR rotafilo odoo.modules.registry: Model report.plm_files.partner has no table.
2018-06-20 11:57:21,413 18 WARNING rotafilo odoo.models: ir.cron.create() includes unknown fields: args, function
2018-06-20 11:57:21,451 18 WARNING rotafilo odoo.models: ir.actions.server.create() includes unknown fields: condition
2018-06-20 11:57:22,044 18 WARNING rotafilo odoo.modules.registry: Models have no table: report.plm_document.user, report.plm_files.partner, report.plm_document.wall.
2018-06-20 11:57:22,050 18 ERROR rotafilo odoo.modules.registry: Model report.plm_document.user has no table.
2018-06-20 11:57:22,050 18 ERROR rotafilo odoo.modules.registry: Model report.plm_document.wall has no table.
2018-06-20 11:57:22,050 18 ERROR rotafilo odoo.modules.registry: Model report.plm_files.partner has no table.
2018-06-20 11:57:22,980 18 WARNING rotafilo odoo.modules.registry: Models have no table: report.plm_document.user, report.plm_files.partner, report.plm_document.wall.
2018-06-20 11:57:22,986 18 ERROR rotafilo odoo.modules.registry: Model report.plm_document.user has no table.
2018-06-20 11:57:22,986 18 ERROR rotafilo odoo.modules.registry: Model report.plm_document.wall has no table.
2018-06-20 11:57:22,986 18 ERROR rotafilo odoo.modules.registry: Model report.plm_files.partner has no table.
2018-06-20 11:57:23,468 18 WARNING rotafilo odoo.modules.loading: The model plm.temporary_date_compute has no access rules, consider adding one. E.g. access_plm_temporary_date_compute,access_plm_temporary_date_compute,model_plm_temporary_date_compute,,1,0,0,0
2018-06-20 11:57:23,469 18 WARNING rotafilo odoo.modules.loading: The model document.rev_wizard has no access rules, consider adding one. E.g. access_document_rev_wizard,access_document_rev_wizard,model_document_rev_wizard,,1,0,0,0
2018-06-20 11:57:23,470 18 WARNING rotafilo odoo.modules.loading: The transient model plm.temporary (Temporary Class) should not have explicit access rules!
2018-06-20 12:00:31,963 16 WARNING rotafilo odoo.modules.registry: Models have no table: report.plm_document.user, report.plm_files.partner, report.plm_document.wall.
2018-06-20 12:00:31,967 16 ERROR rotafilo odoo.modules.registry: Model report.plm_document.user has no table.
2018-06-20 12:00:31,968 16 ERROR rotafilo odoo.modules.registry: Model report.plm_document.wall has no table.
2018-06-20 12:00:31,968 16 ERROR rotafilo odoo.modules.registry: Model report.plm_files.partner has no table.
2018-06-20 12:00:32,249 16 WARNING rotafilo odoo.modules.loading: The model plm.temporary_date_compute has no access rules, consider adding one. E.g. access_plm_temporary_date_compute,access_plm_temporary_date_compute,model_plm_temporary_date_compute,,1,0,0,0
2018-06-20 12:00:32,249 16 WARNING rotafilo odoo.modules.loading: The model document.rev_wizard has no access rules, consider adding one. E.g. access_document_rev_wizard,access_document_rev_wizard,model_document_rev_wizard,,1,0,0,0
2018-06-20 12:00:32,251 16 WARNING rotafilo odoo.modules.loading: The transient model plm.temporary (Temporary Class) should not have explicit access rules!
2018-06-20 12:02:17,905 16 WARNING rotafilo odoo.modules.registry: Models have no table: report.plm_document.user, report.plm_files.partner, report.plm_document.wall.
2018-06-20 12:02:17,932 16 ERROR rotafilo odoo.modules.registry: Model report.plm_document.user has no table.
2018-06-20 12:02:17,932 16 ERROR rotafilo odoo.modules.registry: Model report.plm_document.wall has no table.
2018-06-20 12:02:17,932 16 ERROR rotafilo odoo.modules.registry: Model report.plm_files.partner has no table.
2018-06-20 12:02:18,220 16 WARNING rotafilo odoo.modules.loading: The model plm.temporary_date_compute has no access rules, consider adding one. E.g. access_plm_temporary_date_compute,access_plm_temporary_date_compute,model_plm_temporary_date_compute,,1,0,0,0
2018-06-20 12:02:18,220 16 WARNING rotafilo odoo.modules.loading: The model document.rev_wizard has no access rules, consider adding one. E.g. access_document_rev_wizard,access_document_rev_wizard,model_document_rev_wizard,,1,0,0,0
2018-06-20 12:02:18,222 16 WARNING rotafilo odoo.modules.loading: The transient model plm.temporary (Temporary Class) should not have explicit access rules!
2018-06-20 12:05:04,624 18 INFO rotafilo root: Internal ref set value 98D27803000000_0 on engineering_code: '98D27803000000'
2018-06-20 12:43:33,400 18 INFO rotafilo root: Internal ref set value A32015-9_0 on engineering_code: 'A32015-9'
2018-06-20 13:55:52,218 21 WARNING ? odoo.addons.base.ir.ir_cron: Skipping database rotafilo because of modules to install/upgrade/remove.
2018-06-20 13:56:09,738 22 WARNING ? odoo.addons.base.ir.ir_cron: Skipping database rotafilo because of modules to install/upgrade/remove.
2018-06-20 14:24:52,004 14 ERROR rotafilo odoo.sql_db: bad query: b'ALTER TABLE "mrp_bom_line" ALTER COLUMN "type" SET NOT NULL'
ERROR: column "type" contains null values

2018-06-20 14:24:52,176 14 WARNING rotafilo odoo.schema: Table 'mrp_bom_line': unable to set NOT NULL on column 'type'!
If you want to have it, you should update the records and execute manually:
ALTER TABLE "mrp_bom_line" ALTER COLUMN "type" SET NOT NULL
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/sql.py", line 109, in set_not_null
    cr.execute(query)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.IntegrityError: column "type" contains null values

2018-06-20 14:24:53,334 14 WARNING rotafilo odoo.modules.registry: Models have no table: report.plm_document.user, report.plm_files.partner, report.plm_document.wall.
2018-06-20 14:24:53,338 14 ERROR rotafilo odoo.modules.registry: Model report.plm_document.user has no table.
2018-06-20 14:24:53,338 14 ERROR rotafilo odoo.modules.registry: Model report.plm_document.wall has no table.
2018-06-20 14:24:53,338 14 ERROR rotafilo odoo.modules.registry: Model report.plm_files.partner has no table.
2018-06-20 14:24:56,496 14 WARNING rotafilo odoo.models: ir.actions.act_window.create() includes unknown fields: view_id_search
2018-06-20 14:24:57,179 14 WARNING rotafilo odoo.models: ir.actions.report.create() includes unknown fields: header
2018-06-20 14:24:57,186 14 WARNING rotafilo odoo.models: ir.actions.report.create() includes unknown fields: header
2018-06-20 14:24:57,192 14 WARNING rotafilo odoo.models: ir.actions.report.create() includes unknown fields: header
2018-06-20 14:24:57,197 14 WARNING rotafilo odoo.models: ir.actions.report.create() includes unknown fields: header
2018-06-20 14:24:57,203 14 WARNING rotafilo odoo.models: ir.actions.report.create() includes unknown fields: header
2018-06-20 14:24:57,209 14 WARNING rotafilo odoo.models: ir.actions.report.create() includes unknown fields: header
2018-06-20 14:24:57,218 14 WARNING rotafilo odoo.models: ir.actions.report.create() includes unknown fields: header
2018-06-20 14:24:58,732 14 WARNING rotafilo odoo.modules.registry: Models have no table: report.plm_document.user, report.plm_files.partner, report.plm_document.wall.
2018-06-20 14:24:58,737 14 ERROR rotafilo odoo.modules.registry: Model report.plm_document.user has no table.
2018-06-20 14:24:58,737 14 ERROR rotafilo odoo.modules.registry: Model report.plm_document.wall has no table.
2018-06-20 14:24:58,737 14 ERROR rotafilo odoo.modules.registry: Model report.plm_files.partner has no table.
2018-06-20 14:29:28,621 21 WARNING ? odoo.addons.base.ir.ir_cron: Skipping database rotafilo because of modules to install/upgrade/remove.
2018-06-20 14:29:40,850 18 ERROR rotafilo odoo.modules.graph: module plm_cutted_parts: Unmet dependencies: plm, plm_engineering
2018-06-20 14:29:40,850 18 ERROR rotafilo odoo.modules.graph: module plm_automatic_weight: Unmet dependencies: plm
2018-06-20 14:29:40,850 18 ERROR rotafilo odoo.modules.graph: module plm_automate_normal_bom: Unmet dependencies: plm, plm_engineering
2018-06-20 14:29:40,850 18 ERROR rotafilo odoo.modules.graph: module plm_spare: Unmet dependencies: plm
2018-06-20 14:29:40,850 18 ERROR rotafilo odoo.modules.graph: module plm_report_language_helper: Unmet dependencies: plm, plm_spare
2018-06-20 14:29:40,850 18 ERROR rotafilo odoo.modules.graph: module plm_product_description_language_helper: Unmet dependencies: plm
2018-06-20 14:29:40,850 18 ERROR rotafilo odoo.modules.graph: module plm_web_revision: Unmet dependencies: plm
2018-06-20 14:29:40,850 18 ERROR rotafilo odoo.modules.graph: module plm_auto_internalref: Unmet dependencies: plm
2018-06-20 14:29:40,850 18 ERROR rotafilo odoo.modules.graph: module plm_engineering: Unmet dependencies: plm
2018-06-20 14:29:40,850 18 ERROR rotafilo odoo.modules.graph: module plm_pack_and_go: Unmet dependencies: plm
```

**Comment by OmniaGit** [comment]
fix in v12
