### ISSUE TITLE
[11.0] Odoo Server Error at installing some extra features

### ISSUE THREAD

**Issue by SalahAdDin** [OmniaGit/odooplm#5]
I installed this module in the lastest **Odoo** nightly version, all is well; but, when I'm trying to install/setup extra features, I get this error:

```bash
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 938, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/res/res_config.py", line 564, in execute
    self._install_modules(to_install)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/res/res_config.py", line 35, in _install_modules
    result = to_install_modules.button_immediate_install()
  File "<decorator-gen-48>", line 2, in button_immediate_install
  File "/usr/lib/python3/dist-packages/odoo/addons/base/module/module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/module/module.py", line 449, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/module/module.py", line 542, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 380, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 274, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 152, in load_module_graph
    registry.setup_models(cr)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 277, in setup_models
    model._setup_fields()
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 2425, in _setup_fields
    field.setup_full(self)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 471, in setup_full
    self._setup_related_full(model)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 516, in _setup_related_full
    raise TypeError("Type of related field %s is inconsistent with %s" % (self, field))
TypeError: Type of related field plm.missing.bom.description is inconsistent with product.product.name
```

Why?

`Odoo 11.0-20180904 (Community Edition)`

**UPDATE:**
It happens when I'm trying to enable **Compare two BOM tool** feature:
![deepin-screen-recorder_select area_20180906103034](https://user-images.githubusercontent.com/5034215/45141965-fa3d6e80-b1bf-11e8-9ba9-70932d13d544.gif)

**Comment by OmniaGit** [comment]
Dear Mr. SalahAdDin,
I made some tests and I solved and pushed the solution. Please update your code with the last commit.
Best Regards,
Daniel

**Comment by SalahAdDin** [comment]
@OmniaGit Hi Daniel, the bug was solved, thank you very much.
