### ISSUE TITLE
[11.0][plm_engineering]Engineering BOM does not show CAD item position

### ISSUE THREAD

**Issue by SalahAdDin** [OmniaGit/odooplm#9]
I'm testing this module for my client, it is very good, but i'm looking for some bugs.

In this case, i have one that i want to call crossing concepts: 
![deepin-screen-recorder_select area_20180912173145](https://user-images.githubusercontent.com/5034215/45432236-09d22100-b6b2-11e8-8912-b996d50bae83.gif)

As you can see in the above animation when you see a normal `BOM`, that does not need a `CAD` item position as well other fields, you will find them in the `BOM` view; while, the Engineering `BOM`, that use `CAD` item positions, does not show that field, why?
![faltan estos](https://user-images.githubusercontent.com/5034215/45433257-6fbfa800-b6b4-11e8-9466-105b793d880b.png)

That's why i call it crossing concepts: Normal `BOM` shows a logical engineering `BOM`, while Engineering `BOM` shows a normal `BOM`.

Is there any explanation for that?

**Comment by SalahAdDin** [comment]
I'm trying to fix this problem; i tried with two or three approaches, but finally i have just to remove and add fields; it has a problem: `consumed in operation` is not added in this view.

And also, it has an interesting issue:
![deepin-screen-recorder_select area_20180914163857](https://user-images.githubusercontent.com/5034215/45555434-729bd380-b841-11e8-9be8-dbea2153329f.gif)
As you can see, if i get into the view through `Search on Engineering Bill of Materials` i get the custom view, but if i see the `BoM` through the `Engineering Part` view i get the normal component view.

So, why do you use this kind of view? Is better use the common `BoM` view?

I think the correct solution is to inherit the `Engine BoM` view from normal `BoM`, but only shows its fields in the proper `Engine BoM` view. Actually, I got the next issue:
```bash
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 1036, in _validate_fields
    check(self)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 335, in _check_xml
    self.postprocess_and_fields(view.model, view_doc, view.id)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 1020, in postprocess_and_fields
    fields_def = self.postprocess(model, node, view_id, False, fields)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 845, in postprocess
    fields.update(self.postprocess(model, f, view_id, in_tree_view, model_fields))
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 845, in postprocess
    fields.update(self.postprocess(model, f, view_id, in_tree_view, model_fields))
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 845, in postprocess
    fields.update(self.postprocess(model, f, view_id, in_tree_view, model_fields))
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 845, in postprocess
    fields.update(self.postprocess(model, f, view_id, in_tree_view, model_fields))
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 805, in postprocess
    ).postprocess_and_fields(field.comodel_name, f, view_id)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 1061, in postprocess_and_fields
    self.raise_view_error("\n".join(msg_lines), view_id)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 509, in raise_view_error
    raise ValueError(message)
ValueError: Field 'has_attachments' used in attributes must be present in view but is missing:
 - 'has_attachments' in attrs="{'invisible': [('has_attachments', '=', False)]}"
 - 'has_attachments' in attrs="{'invisible': [('has_attachments', '=', True)]}"

Error context:
View `plm.bom.form.eng`
[view_id: 959, xml_id: plm.plm_bom_form_view_eng, model: mrp.bom, parent_id: n/a]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 744, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 654, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_model.py", line 1448, in _update
    record.write(values)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 414, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3107, in write
    field.determine_inverse(records)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1071, in determine_inverse
    getattr(records, self.inverse)()
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 266, in _inverse_arch
    view.write(data)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 414, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3089, in write
    self._write(old_vals)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3255, in _write
    self._validate_fields(vals)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 1040, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.exceptions.ValidationError: ('Error while validating constraint\n\nField \'has_attachments\' used in attributes must be present in view but is missing:\n - \'has_attachments\' in attrs="{\'invisible\': [(\'has_attachments\', \'=\', False)]}"\n - \'has_attachments\' in attrs="{\'invisible\': [(\'has_attachments\', \'=\', True)]}"\n\nError context:\nView `plm.bom.form.eng`\n[view_id: 959, xml_id: plm.plm_bom_form_view_eng, model: mrp.bom, parent_id: n/a]', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 938, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-54>", line 2, in button_immediate_upgrade
  File "/usr/lib/python3/dist-packages/odoo/addons/base/module/module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/module/module.py", line 603, in button_immediate_upgrade
    return self._button_immediate_function(type(self).button_upgrade)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/module/module.py", line 542, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 376, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 274, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 181, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 791, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 852, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 751, in parse
    exc_info[2]
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 744, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 654, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_model.py", line 1448, in _update
    record.write(values)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 414, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3107, in write
    field.determine_inverse(records)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1071, in determine_inverse
    getattr(records, self.inverse)()
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 266, in _inverse_arch
    view.write(data)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 414, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3089, in write
    self._write(old_vals)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3255, in _write
    self._validate_fields(vals)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 1040, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.tools.convert.ParseError: "Error while validating constraint

Field 'has_attachments' used in attributes must be present in view but is missing:
 - 'has_attachments' in attrs="{'invisible': [('has_attachments', '=', False)]}"
 - 'has_attachments' in attrs="{'invisible': [('has_attachments', '=', True)]}"
```

It is a problem, because, at least in my client's company, engineers need to attach some file to the `BoM` components.

**Comment by SalahAdDin** [comment]
I think the correct solution is to inherit the `Engine BoM` view from normal `BoM`, but only shows its fields in the proper `Engine BoM` view.

**Comment by SalahAdDin** [comment]
Also, i can see you can create normal `BoM` since engineering `BoM` section, it is ...

**Comment by OmniaGit** [comment]
fix in v12
